#!/usr/bin/env python3
"""Generate examples.js for the playground from the CTest sample programs.

The table below mirrors the add_crabber_test / add_test invocations in the
top-level CMakeLists.txt. test-7-boxes is intentionally omitted: the boxes
domain needs the LDD library, which is not part of the WASM build.

Run:  ./gen-examples.py       (writes ./examples.js)
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SAMPLES = os.path.join(HERE, os.pardir, "samples")
OUT = os.path.join(HERE, "examples.js")

# (label, sample file, domain, extra flags)  -- keep in sync with CMakeLists.txt
TESTS = [
    ("Counter loops · intervals",            "test-1.crabir",      "int",            ""),
    ("Nested loops · intervals",             "test-3.crabir",      "int",            ""),
    ("Relational bound x+y · octagons",      "test-4.crabir",      "oct-snf",        ""),
    ("Widening thresholds · intervals",      "test-5.crabir",      "int",            "--widening-thresholds 10"),
    ("Booleans & casts · intervals",         "test-6.crabir",      "int",            ""),
    ("Value partitioning · powerset int",    "test-7.crabir",      "int-set",        "--widening-delay 10"),
    ("Value partitioning · val-part int",    "test-7.crabir",      "int-val-part",   "--widening-delay 10"),
    ("Value partitioning · val-part zones",  "test-7.crabir",      "zones-val-part", "--widening-delay 10"),
    ("Array load/store · zones",             "test-8.crabir",      "zones",          ""),
    ("Non-unit coefficients · non-unit oct", "test-9.crabir",      "non-unit-oct",   "--coefficients 4,8"),
    ("Symbolic terms · intervals+terms",     "test-10.crabir",     "int-terms",      ""),
    ("Function call: 1-in/1-out · zones",    "test-call-1.crabir", "zones",          ""),
    ("Function call: multi in/out · zones",  "test-call-2.crabir", "zones",          ""),
    ("Function call: void call · zones",     "test-call-3.crabir", "zones",          ""),
    ("Function call: reused callee · zones", "test-call-4.crabir", "zones",          ""),
]

examples = []
for name, fname, domain, flags in TESTS:
    path = os.path.join(SAMPLES, fname)
    if not os.path.isfile(path):
        sys.exit(f"error: sample not found: {path}")
    with open(path, encoding="utf-8") as f:
        code = f.read()
    examples.append({"name": name, "file": fname, "domain": domain,
                     "flags": flags, "code": code})

with open(OUT, "w", encoding="utf-8") as f:
    f.write("// AUTO-GENERATED by gen-examples.py from ../samples + the CMakeLists CTest table.\n")
    f.write("// Do not edit by hand; run ./gen-examples.py to regenerate.\n")
    f.write("window.CRABIR_EXAMPLES = ")
    json.dump(examples, f, ensure_ascii=False, indent=1)
    f.write(";\n")

print(f">> wrote {OUT} ({len(examples)} examples)")
