#!/usr/bin/env python3
"""Generate examples.js for the playground from the CTest sample programs.

The table below mirrors the add_crabber_test / add_test invocations in the
top-level CMakeLists.txt. test-7-boxes is intentionally omitted: the boxes
domain needs the LDD library, which is not part of the WASM build.

Run:  ./gen-examples.py       (writes ./examples.js)
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SAMPLES = os.path.join(HERE, os.pardir, "samples")
OUT = os.path.join(HERE, "examples.js")

# (label, sample file, domain, extra flags)  -- keep in sync with CMakeLists.txt
TESTS = [
    ("test-1 · intervals",            "test-1.crabir",      "int",            ""),
    ("test-3 · intervals",            "test-3.crabir",      "int",            ""),
    ("test-4 · octagons (snf)",       "test-4.crabir",      "oct-snf",        ""),
    ("test-5 · widening thresholds",  "test-5.crabir",      "int",            "--widening-thresholds 10"),
    ("test-6 · intervals",            "test-6.crabir",      "int",            ""),
    ("test-7 · powerset intervals",   "test-7.crabir",      "int-set",        "--widening-delay 10"),
    ("test-7 · val-part intervals",   "test-7.crabir",      "int-val-part",   "--widening-delay 10"),
    ("test-7 · val-part zones",       "test-7.crabir",      "zones-val-part", "--widening-delay 10"),
    ("test-8 · zones",                "test-8.crabir",      "zones",          ""),
    ("test-9 · non-unit octagons",    "test-9.crabir",      "non-unit-oct",   "--coefficients 4,8"),
    ("test-10 · int + terms",         "test-10.crabir",     "int-terms",      ""),
    ("test-call-1 · zones",           "test-call-1.crabir", "zones",          ""),
    ("test-call-2 · zones",           "test-call-2.crabir", "zones",          ""),
    ("test-call-3 · zones",           "test-call-3.crabir", "zones",          ""),
    ("test-call-4 · zones",           "test-call-4.crabir", "zones",          ""),
]

examples = []
for name, fname, domain, flags in TESTS:
    path = os.path.join(SAMPLES, fname)
    if not os.path.isfile(path):
        sys.exit(f"error: sample not found: {path}")
    with open(path, encoding="utf-8") as f:
        code = f.read()
    examples.append({"name": name, "file": fname, "domain": domain,
                     "flags": flags, "code": code})

with open(OUT, "w", encoding="utf-8") as f:
    f.write("// AUTO-GENERATED by gen-examples.py from ../samples + the CMakeLists CTest table.\n")
    f.write("// Do not edit by hand; run ./gen-examples.py to regenerate.\n")
    f.write("window.CRABIR_EXAMPLES = ")
    json.dump(examples, f, ensure_ascii=False, indent=1)
    f.write(";\n")

print(f">> wrote {OUT} ({len(examples)} examples)")
